import type {
  CuratedExampleKnowledgeContract,
  PluginKnowledgeContract,
  RecipeKnowledgeContract,
  TroubleshootingKnowledgeContract,
} from '../contracts'

const DOC_IDS = {
  gettingStarted: 'doc:/docs/concepts/getting-started',
  directives: 'doc:/docs/guides/directives',
  mcpServerSetup: 'doc:/mcp/setup',
  polymorphicBlocks: 'doc:/docs/guides/polymorphic-blocks',
  schemaDesign: 'doc:/docs/guides/schema-design',
  writingAPlugin: 'doc:/docs/reference/writing-a-plugin',
} as const

const EXAMPLE_IDS = {
  modelToSchema: 'example:model-to-schema:user-orders-basic',
  queryLookahead: 'example:query-lookahead:me-with-orders',
  polymorphicBlocks: 'example:polymorphic-blocks:page-blocks-basic',
  directiveMiddleware: 'example:directive-middleware:user-auth-directive',
  schemaInspection: 'example:schema-inspection:generate-schema-artifacts',
  generatedQuery: 'example:generated-query:products-filters-order-pagination',
  customMutation: 'example:custom-mutation:register-prospect',
  customPlugin: 'example:custom-plugin:sequelize-reference-study',
} as const

const RECIPE_IDS = {
  sequelizeBootstrap: 'recipe:sequelize-bootstrap',
  inspectGeneratedSchemaArtifacts: 'recipe:inspect-generated-schema-artifacts',
  generatedQueryFields: 'recipe:add-generated-query-fields',
  generatedFiltersOrderPagination: 'recipe:generated-filters-order-pagination',
  queryLookaheadShape: 'recipe:query-lookahead-shape',
  customQueryOrMutation: 'recipe:custom-query-or-mutation',
  cacheFriendlyMutationPayloads: 'recipe:cache-friendly-mutation-payloads',
  directiveMiddlewareAuth: 'recipe:directive-middleware-auth',
  polymorphicContentBlocks: 'recipe:polymorphic-content-blocks',
  customPluginEvaluation: 'recipe:custom-plugin-evaluation',
  writeMinimalCustomPlugin: 'recipe:write-minimal-custom-plugin',
} as const

const siteCuratedExampleKnowledge: CuratedExampleKnowledgeContract[] = [
  {
    id: 'generate-schema-artifacts',
    scenario: 'schema-inspection',
    title: 'Inspect Generated Schema Artifacts',
    summary: 'Use schemaString and schemaHtml from generateSchema to review SDL before runtime integration.',
    description: 'GraphQL Gene exposes schema inspection artifacts so the team can validate SDL, directives, aliases, and root fields before debugging server behavior.',
    editableFields: ['schemaString', 'schemaHtml', 'developmentOnly'],
    topics: ['schema', 'inspection', 'sdl', 'schemaString', 'schemaHtml'],
    sourcePath: 'node_modules/graphql-gene/README.md',
    recommendedDocIds: [DOC_IDS.gettingStarted],
    codeSourcePath: 'node_modules/graphql-gene/README.md',
    executionMode: 'canonical',
    supportsDisplayedCodeParity: true,
    supportsRuntimeParity: true,
    suitableSurfaces: ['docs', 'mcp'],
    confidence: 'high',
  },
  {
    id: 'products-filters-order-pagination',
    scenario: 'generated-query',
    title: 'Generated Query With Filters, Order, and Pagination',
    summary: 'Expose a default Query field and let GraphQL Gene generate where, order, page, and perPage arguments.',
    description: 'The default resolver path can own generated query fields and nested association filters, reducing the need for hand-written query resolvers.',
    editableFields: ['resolver', 'where', 'order', 'page', 'perPage'],
    topics: ['query', 'filtering', 'ordering', 'pagination', 'default-resolver', 'operators'],
    sourcePath: 'node_modules/graphql-gene/README.md',
    recommendedDocIds: [DOC_IDS.gettingStarted, DOC_IDS.schemaDesign],
    codeSourcePath: 'node_modules/graphql-gene/README.md',
    executionMode: 'canonical',
    supportsDisplayedCodeParity: true,
    supportsRuntimeParity: true,
    suitableSurfaces: ['docs', 'mcp'],
    confidence: 'high',
  },
  {
    id: 'register-prospect',
    scenario: 'custom-mutation',
    title: 'Register Prospect Custom Mutation',
    summary: 'Define a typed custom mutation with extendTypes, explicit args, and a declared return type.',
    description: 'When the default resolver path is not enough, GraphQL Gene still lets you define custom Query or Mutation fields while keeping schema ownership and typing in one place.',
    editableFields: ['args', 'returnType', 'resolver'],
    topics: ['mutation', 'query', 'extendTypes', 'custom-resolver', 'returnType'],
    sourcePath: 'node_modules/graphql-gene/README.md',
    recommendedDocIds: [DOC_IDS.gettingStarted, DOC_IDS.schemaDesign],
    codeSourcePath: 'node_modules/graphql-gene/README.md',
    executionMode: 'canonical',
    supportsDisplayedCodeParity: true,
    supportsRuntimeParity: true,
    suitableSurfaces: ['docs', 'mcp'],
    confidence: 'high',
  },
  {
    id: 'sequelize-reference-study',
    scenario: 'custom-plugin',
    title: 'Study The Sequelize Plugin As A Reference',
    summary: 'Use the Sequelize plugin as the reference implementation before building a custom plugin for another ORM.',
    description: 'The custom plugin path should start by studying how pluginSequelize hooks into generateSchema, derives GraphQL fields, and handles lookahead-related behavior.',
    editableFields: ['pluginFactory', 'types', 'plugins'],
    topics: ['plugin', 'custom-plugin', 'reference-implementation', 'sequelize', 'generateSchema'],
    sourcePath: 'content/graphql-gene/docs/writing-a-plugin.md',
    recommendedDocIds: [DOC_IDS.writingAPlugin, DOC_IDS.schemaDesign],
    codeSourcePath: 'content/graphql-gene/docs/writing-a-plugin.md',
    executionMode: 'canonical',
    supportsDisplayedCodeParity: true,
    supportsRuntimeParity: true,
    suitableSurfaces: ['docs', 'mcp'],
    confidence: 'high',
  },
]

const sitePluginKnowledge: PluginKnowledgeContract[] = [
  {
    id: 'sequelize',
    title: 'Sequelize Plugin',
    summary: 'The first-class GraphQL Gene plugin path for generating a schema directly from Sequelize models.',
    description: 'Use the documented Sequelize integration when your data model already lives in Sequelize and you want automatic schema generation, default CRUD resolvers, and query lookahead from one plugin path.',
    topics: ['plugin', 'sequelize', 'schema', 'lookahead', 'orm-native'],
    sourcePath: 'content/graphql-gene/docs/getting-started.md',
    packageName: '@graphql-gene/plugin-sequelize',
    supportedOrms: ['Sequelize'],
    scenarios: ['model-to-schema', 'query-lookahead'],
    whenToUse: [
      'Your Sequelize models are the source of truth for the GraphQL API.',
      'You want the documented production path already covered by this repo.',
      'You want automatic schema generation plus query lookahead without building a custom plugin first.',
    ],
    whenNotToUse: [
      'Your data layer is not Sequelize and cannot be adapted to the Sequelize plugin assumptions.',
      'You already know you need custom plugin behavior outside the documented Sequelize path.',
    ],
    recommendedDocIds: [DOC_IDS.gettingStarted, DOC_IDS.schemaDesign],
    recommendedExampleIds: [EXAMPLE_IDS.modelToSchema, EXAMPLE_IDS.queryLookahead, EXAMPLE_IDS.generatedQuery, EXAMPLE_IDS.schemaInspection],
    recommendedRecipeIds: [RECIPE_IDS.sequelizeBootstrap, RECIPE_IDS.generatedFiltersOrderPagination, RECIPE_IDS.queryLookaheadShape, RECIPE_IDS.inspectGeneratedSchemaArtifacts],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'custom-plugin',
    title: 'Custom Plugin Authoring',
    summary: 'Use the GraphQL Gene plugin API when your ORM or backend does not fit the Sequelize integration path.',
    description: 'Study the Sequelize plugin as the reference implementation, then author a narrower custom plugin for the target ORM or backend surface instead of forcing an unsupported Sequelize mapping.',
    topics: ['plugin', 'custom-plugin', 'orm', 'integration', 'advanced'],
    sourcePath: 'content/graphql-gene/docs/writing-a-plugin.md',
    supportedOrms: ['Custom ORM', 'Non-Sequelize data layer'],
    scenarios: ['model-to-schema'],
    whenToUse: [
      'The target ORM is not Sequelize.',
      'The GraphQL model graph needs plugin behavior not covered by the documented Sequelize integration.',
      'You need explicit control over how GraphQL Gene derives types or runtime behavior from the backend model layer.',
    ],
    whenNotToUse: [
      'The documented Sequelize plugin already matches the project architecture.',
      'The need for a custom plugin has not been validated against the current docs and reference implementation.',
    ],
    recommendedDocIds: [DOC_IDS.writingAPlugin, DOC_IDS.schemaDesign],
    recommendedExampleIds: [EXAMPLE_IDS.customPlugin, EXAMPLE_IDS.customMutation],
    recommendedRecipeIds: [RECIPE_IDS.customPluginEvaluation, RECIPE_IDS.writeMinimalCustomPlugin],
    stability: 'stable',
    confidence: 'high',
  },
]

const siteRecipeKnowledge: RecipeKnowledgeContract[] = [
  {
    id: 'sequelize-bootstrap',
    title: 'Bootstrap GraphQL Gene With Sequelize',
    summary: 'Install GraphQL Gene, wire the Sequelize plugin, export your GraphQL types, and generate the first executable schema.',
    description: 'This is the shortest path from Sequelize models to a working GraphQL Gene schema and should be the default recommendation for first-time adoption in Sequelize projects.',
    topics: ['recipe', 'getting-started', 'sequelize', 'schema'],
    sourcePath: 'content/graphql-gene/docs/getting-started.md',
    goal: 'Generate the first GraphQL Gene schema from Sequelize models and attach it to a GraphQL server.',
    serverStacks: ['Apollo Server', 'GraphQL Yoga', 'Mercurius'],
    orms: ['Sequelize'],
    scenarios: ['model-to-schema'],
    steps: [
      'Install graphql-gene and @graphql-gene/plugin-sequelize.',
      'Re-export every GraphQL Gene type from one canonical module.',
      'Call generateSchema with pluginSequelize() and the exported types object.',
      'Attach the generated schema to the GraphQL server once the SDL looks correct.',
    ],
    recommendedPluginIds: ['plugin:sequelize'],
    recommendedDocIds: [DOC_IDS.gettingStarted],
    recommendedExampleIds: [EXAMPLE_IDS.modelToSchema],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'inspect-generated-schema-artifacts',
    title: 'Inspect Generated Schema Before Server Wiring',
    summary: 'Use schemaString and schemaHtml to validate SDL before debugging the GraphQL server runtime.',
    description: 'Treat generated schema inspection as a required checkpoint so missing types, directives, and aliases are found before runtime debugging begins.',
    topics: ['recipe', 'schema', 'inspection', 'sdl'],
    sourcePath: 'node_modules/graphql-gene/README.md',
    goal: 'Inspect generated GraphQL SDL and schema artifacts as part of the normal GraphQL Gene workflow.',
    serverStacks: ['Fastify', 'Apollo Server', 'GraphQL Yoga', 'Mercurius'],
    orms: ['Sequelize', 'Custom ORM'],
    scenarios: ['model-to-schema'],
    steps: [
      'Capture schemaString or schemaHtml from generateSchema in the schema entrypoint.',
      'Write schemaString to a local ignored artifact or expose schemaHtml through a development-only endpoint.',
      'Compare expected types, directives, aliases, and root fields before attaching the schema to the main server runtime.',
      'Use SDL inspection as the first debugging step whenever generated output seems incomplete.',
    ],
    recommendedPluginIds: ['plugin:sequelize', 'plugin:custom-plugin'],
    recommendedDocIds: [DOC_IDS.gettingStarted],
    recommendedExampleIds: [EXAMPLE_IDS.schemaInspection],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'add-generated-query-fields',
    title: 'Expose Generated Query Fields With The Default Resolver',
    summary: 'Use extendTypes and resolver: default to add root query fields without hand-writing the full resolver path.',
    description: 'This recipe keeps root field authoring close to GraphQL Gene generation, so filtering and association traversal remain source-backed instead of being rebuilt manually.',
    topics: ['recipe', 'query', 'default-resolver', 'extendTypes'],
    sourcePath: 'node_modules/graphql-gene/README.md',
    goal: 'Add Query fields whose arguments and resolution stay aligned with GraphQL Gene default behavior.',
    serverStacks: ['Apollo Server', 'GraphQL Yoga', 'Mercurius'],
    orms: ['Sequelize', 'Custom ORM'],
    scenarios: ['model-to-schema', 'query-lookahead'],
    steps: [
      'Define the root field with extendTypes on Query or Mutation.',
      'Use resolver: default when GraphQL Gene should own list loading and filter argument generation.',
      'Set an explicit returnType that matches the intended model or helper type.',
      'Inspect the generated SDL before deciding whether custom logic is still necessary.',
    ],
    recommendedPluginIds: ['plugin:sequelize', 'plugin:custom-plugin'],
    recommendedDocIds: [DOC_IDS.gettingStarted, DOC_IDS.schemaDesign],
    recommendedExampleIds: [EXAMPLE_IDS.generatedQuery],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'generated-filters-order-pagination',
    title: 'Use Generated Filters, Order, and Pagination',
    summary: 'Design list and association queries around the generated where, order, page, and perPage arguments.',
    description: 'Prefer upstream-supported generated filtering over manual input re-implementation so operators and pagination semantics stay consistent across root and nested fields.',
    topics: ['recipe', 'filtering', 'ordering', 'pagination', 'operators'],
    sourcePath: 'node_modules/graphql-gene/README.md',
    goal: 'Expose filtering, ordering, and pagination through generated GraphQL Gene arguments.',
    serverStacks: ['Apollo Server', 'GraphQL Yoga', 'Mercurius'],
    orms: ['Sequelize'],
    scenarios: ['query-lookahead'],
    steps: [
      'Start from a default resolver-backed field rather than a custom query resolver.',
      'Use where, order, page, and perPage instead of rebuilding equivalent GraphQL inputs by hand.',
      'Apply nested filters on association fields where the graph needs them.',
      'Inspect SQL or include behavior when query shape and runtime loading diverge.',
    ],
    recommendedPluginIds: ['plugin:sequelize'],
    recommendedDocIds: [DOC_IDS.gettingStarted, DOC_IDS.schemaDesign],
    recommendedExampleIds: [EXAMPLE_IDS.generatedQuery, EXAMPLE_IDS.queryLookahead],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'query-lookahead-shape',
    title: 'Design Queries For Lookahead-Friendly Resolution',
    summary: 'Shape the schema and GraphQL operations so the default resolver path can load only the associations selected by the client.',
    description: 'Use the documented schema design patterns to stay near default resolution, avoid unnecessary custom resolvers, and let the Sequelize plugin build targeted includes from the selection set.',
    topics: ['recipe', 'lookahead', 'query', 'performance'],
    sourcePath: 'content/graphql-gene/docs/schema-design.md',
    goal: 'Keep nested GraphQL queries aligned with GraphQL Gene lookahead and default resolver behavior.',
    serverStacks: ['Apollo Server', 'GraphQL Yoga', 'Mercurius'],
    orms: ['Sequelize'],
    scenarios: ['query-lookahead'],
    steps: [
      'Model the graph so the default resolver path can see the associations the client will traverse.',
      'Prefer default resolution and query includes over custom resolvers that duplicate core plugin behavior.',
      'Inspect the generated SQL or include graph when nested query performance is unclear.',
      'Paginate hot list fields before they become unbounded performance traps.',
    ],
    recommendedPluginIds: ['plugin:sequelize'],
    recommendedDocIds: [DOC_IDS.schemaDesign, DOC_IDS.gettingStarted],
    recommendedExampleIds: [EXAMPLE_IDS.queryLookahead],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'custom-query-or-mutation',
    title: 'Add A Custom Query Or Mutation With extendTypes',
    summary: 'Define custom Query or Mutation fields with typed args, returnType, and resolver logic inside GraphQL Gene.',
    description: 'Use this recipe when the default resolver path is insufficient but you still want GraphQL Gene to own the field contract and type system.',
    topics: ['recipe', 'mutation', 'query', 'extendTypes', 'custom-resolver'],
    sourcePath: 'node_modules/graphql-gene/README.md',
    goal: 'Add custom Query or Mutation behavior without splitting schema ownership into a separate manual layer.',
    serverStacks: ['Apollo Server', 'GraphQL Yoga', 'Mercurius'],
    orms: ['Sequelize', 'Custom ORM'],
    scenarios: ['model-to-schema'],
    steps: [
      'Define explicit args and returnType for the new field through extendTypes.',
      'Keep the return type aligned with GraphQL Gene object, enum, or helper types.',
      'Implement resolver logic with the typed args contract instead of loosely typed runtime parsing.',
      'Inspect the generated SDL and add runtime tests for the custom field path.',
    ],
    recommendedPluginIds: ['plugin:sequelize', 'plugin:custom-plugin'],
    recommendedDocIds: [DOC_IDS.gettingStarted, DOC_IDS.schemaDesign],
    recommendedExampleIds: [EXAMPLE_IDS.customMutation],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'cache-friendly-mutation-payloads',
    title: 'Return Cache-Friendly Mutation Payloads',
    summary: 'Return modified objects with stable identity so normalized caches can merge updates without avoidable refetches.',
    description: 'Use entity-oriented payloads for mutations that change persisted data, especially when Apollo Client, urql, Relay, or another normalized cache must reconcile updates.',
    topics: ['recipe', 'mutation', 'cache', 'client', 'payloads'],
    sourcePath: 'content/graphql-gene/docs/schema-design.md',
    goal: 'Design mutation return shapes that help client caches update predictably.',
    serverStacks: ['Apollo Server', 'GraphQL Yoga', 'Mercurius'],
    orms: ['Sequelize', 'Custom ORM'],
    scenarios: ['model-to-schema'],
    steps: [
      'Return the modified object or a payload that includes the modified object for entity-changing mutations.',
      'Ensure stable identity such as id and __typename can be recovered by the client cache.',
      'Avoid status-only payloads when the client needs to merge entity changes locally.',
      'Validate the payload shape against the consuming client cache strategy before treating the mutation contract as complete.',
    ],
    recommendedPluginIds: ['plugin:sequelize', 'plugin:custom-plugin'],
    recommendedDocIds: [DOC_IDS.schemaDesign],
    recommendedExampleIds: [EXAMPLE_IDS.customMutation],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'directive-middleware-auth',
    title: 'Attach Runtime Middleware With Directives',
    summary: 'Model auth and other middleware with Gene directives at the type or field level.',
    description: 'Use directives when the runtime behavior should stay close to the schema, whether the directive prints into SDL or remains runtime-only.',
    topics: ['recipe', 'directives', 'middleware', 'auth'],
    sourcePath: 'content/graphql-gene/docs/directives.md',
    goal: 'Add auth or runtime middleware behavior through GraphQL Gene directives.',
    serverStacks: ['Apollo Server', 'GraphQL Yoga', 'Mercurius'],
    orms: ['Sequelize'],
    scenarios: ['directive-middleware'],
    steps: [
      'Define the directive handler around the GraphQL Gene resolver lifecycle.',
      'Decide whether the directive name should print into SDL or stay runtime-only.',
      'Attach the directive at the type or field level that owns the behavior.',
      'Validate the runtime behavior against the generated SDL and directive example.',
    ],
    recommendedPluginIds: ['plugin:sequelize'],
    recommendedDocIds: [DOC_IDS.directives, DOC_IDS.schemaDesign],
    recommendedExampleIds: [EXAMPLE_IDS.directiveMiddleware],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'polymorphic-content-blocks',
    title: 'Model Polymorphic Content Blocks',
    summary: 'Use GraphQL Gene to expose heterogeneous page blocks through one fragment-friendly GraphQL list.',
    description: 'Follow the documented polymorphic blocks pattern when a CMS-style page needs one ordered block list with multiple concrete block types selected through inline fragments.',
    topics: ['recipe', 'polymorphic', 'blocks', 'cms', 'fragments'],
    sourcePath: 'content/graphql-gene/docs/polymorphic-blocks.md',
    goal: 'Expose fragment-friendly polymorphic blocks without drifting away from the upstream model graph.',
    serverStacks: ['Apollo Server', 'GraphQL Yoga', 'Mercurius'],
    orms: ['Sequelize'],
    scenarios: ['polymorphic-blocks'],
    steps: [
      'Model the hub row that orders or groups concrete block records.',
      'List the concrete block models once so the decorator can wire the polymorphic behavior.',
      'Query the result with __typename and inline fragments for each concrete block type.',
      'Validate the runtime behavior against the upstream-aligned example rather than treating the playground as primary truth.',
    ],
    recommendedPluginIds: ['plugin:sequelize'],
    recommendedDocIds: [DOC_IDS.polymorphicBlocks, DOC_IDS.directives],
    recommendedExampleIds: [EXAMPLE_IDS.polymorphicBlocks],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'custom-plugin-evaluation',
    title: 'Evaluate Whether You Need A Custom Plugin',
    summary: 'Compare the project ORM and behavior requirements against the Sequelize reference path before committing to custom plugin work.',
    description: 'Use this recipe when the team is unsure whether to stay on the documented Sequelize plugin path or invest in a narrower custom plugin for another backend system.',
    topics: ['recipe', 'plugin', 'decision', 'custom-plugin'],
    sourcePath: 'content/graphql-gene/docs/writing-a-plugin.md',
    goal: 'Decide between the Sequelize integration path and a custom GraphQL Gene plugin.',
    serverStacks: ['Apollo Server', 'GraphQL Yoga', 'Mercurius'],
    orms: ['Sequelize', 'Custom ORM'],
    scenarios: ['model-to-schema'],
    steps: [
      'Confirm whether the backend data layer is genuinely compatible with Sequelize plugin assumptions.',
      'Study the Sequelize plugin as the reference implementation before designing new abstractions.',
      'List the minimum unsupported capabilities that would justify a custom plugin.',
      'Keep the first custom plugin version narrow and source-backed.',
    ],
    recommendedPluginIds: ['plugin:sequelize', 'plugin:custom-plugin'],
    recommendedDocIds: [DOC_IDS.writingAPlugin, DOC_IDS.gettingStarted],
    recommendedExampleIds: [EXAMPLE_IDS.customPlugin],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'write-minimal-custom-plugin',
    title: 'Write A Minimal Custom Plugin',
    summary: 'Start from the Sequelize reference implementation and prove the smallest custom plugin surface that your ORM needs.',
    description: 'This recipe keeps custom plugin authoring narrow, testable, and upstream-aware instead of jumping directly to a broad abstraction.',
    topics: ['recipe', 'plugin', 'custom-plugin', 'reference-implementation'],
    sourcePath: 'content/graphql-gene/docs/writing-a-plugin.md',
    goal: 'Author a first custom GraphQL Gene plugin with the minimum viable capability set.',
    serverStacks: ['Apollo Server', 'GraphQL Yoga', 'Mercurius'],
    orms: ['Custom ORM'],
    scenarios: ['model-to-schema'],
    steps: [
      'Study pluginSequelize as the reference implementation before designing new abstractions.',
      'List the smallest missing capabilities your ORM needs from a plugin.',
      'Implement a narrow plugin factory and validate it against one model graph first.',
      'Add tests for generated schema behavior before expanding into broader runtime features.',
    ],
    recommendedPluginIds: ['plugin:custom-plugin'],
    recommendedDocIds: [DOC_IDS.writingAPlugin, DOC_IDS.schemaDesign],
    recommendedExampleIds: [EXAMPLE_IDS.customPlugin],
    stability: 'stable',
    confidence: 'high',
  },
]

const siteTroubleshootingKnowledge: TroubleshootingKnowledgeContract[] = [
  {
    id: 'missing-types-in-generated-schema',
    title: 'Generated Schema Is Missing Expected Types',
    summary: 'Expected models or object types are absent from the generated schema output.',
    description: 'This issue usually means the canonical GraphQL types module is incomplete or the schema generation input is not pointing at the exports you think it is.',
    topics: ['troubleshooting', 'schema', 'types', 'exports'],
    sourcePath: 'content/graphql-gene/docs/getting-started.md',
    symptoms: [
      'Expected models are missing from the generated SDL.',
      'The generated schema contains only part of the intended GraphQL model graph.',
    ],
    stages: ['install', 'schema'],
    scenarios: ['model-to-schema'],
    likelyCauses: [
      'Not every GraphQL Gene type is re-exported from one canonical module.',
      'The generated schema is built from the wrong types object or an incomplete module.',
    ],
    recommendedChecks: [
      'Inspect the types export module and verify every intended GraphQL Gene type is re-exported.',
      'Generate and inspect the SDL before debugging downstream server wiring.',
      'Compare the setup against the documented Getting Started flow.',
    ],
    recommendedDocIds: [DOC_IDS.gettingStarted],
    recommendedExampleIds: [EXAMPLE_IDS.modelToSchema, EXAMPLE_IDS.schemaInspection],
    recommendedRecipeIds: [RECIPE_IDS.sequelizeBootstrap, RECIPE_IDS.inspectGeneratedSchemaArtifacts],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'directive-not-printed-in-sdl',
    title: 'Directive Middleware Runs But Does Not Appear In SDL',
    summary: 'The directive handler seems active, but the generated schema string does not show the directive annotation.',
    description: 'GraphQL Gene can run directive middleware without printing a directive into SDL, so the most common root cause is an empty directive name or a mismatch between runtime-only and schema-visible expectations.',
    topics: ['troubleshooting', 'directive', 'sdl', 'middleware'],
    sourcePath: 'content/graphql-gene/docs/directives.md',
    symptoms: [
      'The directive behavior works at runtime but @directive is missing from the generated SDL.',
      'The team expects a directive definition in the schema string and cannot find it.',
    ],
    stages: ['directive', 'runtime'],
    scenarios: ['directive-middleware'],
    likelyCauses: [
      'The directive uses an empty name so it stays runtime-only.',
      'The directive was attached at the wrong type or field level.',
    ],
    recommendedChecks: [
      'Confirm whether the directive should print into SDL or remain runtime-only.',
      'Inspect the directive name and handler placement on the relevant type or field.',
      'Compare the result against the directive example and docs.',
    ],
    recommendedDocIds: [DOC_IDS.directives],
    recommendedExampleIds: [EXAMPLE_IDS.directiveMiddleware],
    recommendedRecipeIds: [RECIPE_IDS.directiveMiddlewareAuth],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'wrong-plugin-path-for-orm',
    title: 'Chosen Plugin Path Does Not Match The ORM',
    summary: 'The project is trying to force a non-Sequelize backend through the Sequelize reference integration.',
    description: 'When the target ORM is not Sequelize, GraphQL Gene guidance should usually pivot to custom plugin evaluation rather than stretching the documented Sequelize path beyond its intended surface.',
    topics: ['troubleshooting', 'plugin', 'orm', 'custom-plugin'],
    sourcePath: 'content/graphql-gene/docs/writing-a-plugin.md',
    symptoms: [
      'The target ORM is not Sequelize but the setup still depends on @graphql-gene/plugin-sequelize.',
      'The team is unsure whether to extend the reference plugin or author a custom one.',
    ],
    stages: ['plugin', 'schema'],
    scenarios: ['model-to-schema'],
    likelyCauses: [
      'The ORM decision was made before validating the documented plugin surface.',
      'The project requires backend behaviors that do not map cleanly to the Sequelize plugin assumptions.',
    ],
    recommendedChecks: [
      'Confirm whether Sequelize is truly the target model layer.',
      'Study the Writing a Plugin reference before adding unsupported behavior to the Sequelize path.',
      'List the exact missing capabilities that would justify a custom plugin.',
    ],
    recommendedDocIds: [DOC_IDS.writingAPlugin, DOC_IDS.gettingStarted],
    recommendedExampleIds: [EXAMPLE_IDS.customPlugin],
    recommendedRecipeIds: [RECIPE_IDS.customPluginEvaluation, RECIPE_IDS.writeMinimalCustomPlugin],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'lookahead-behavior-does-not-match-expectation',
    title: 'Lookahead Behavior Does Not Match Query Expectations',
    summary: 'Nested associations are not loading the way the team expects, or the SQL shape looks surprising.',
    description: 'This usually happens when custom resolvers drift away from the default GraphQL Gene resolution path or when the GraphQL operation shape does not align with the intended association graph.',
    topics: ['troubleshooting', 'lookahead', 'query', 'performance'],
    sourcePath: 'content/graphql-gene/docs/schema-design.md',
    symptoms: [
      'The SQL or include graph does not reflect the fields selected by the client.',
      'The team sees unexpected association loading or performance regressions on nested queries.',
    ],
    stages: ['query', 'runtime'],
    scenarios: ['query-lookahead'],
    likelyCauses: [
      'A custom resolver bypasses the default lookahead-aware behavior.',
      'The GraphQL graph or operation shape does not match the intended associations.',
    ],
    recommendedChecks: [
      'Compare the operation against the documented query-lookahead pattern.',
      'Inspect whether the runtime path is canonical or adapted before drawing product-level conclusions.',
      'Reduce custom resolver logic until the default resolution path is understood.',
    ],
    recommendedDocIds: [DOC_IDS.schemaDesign, DOC_IDS.gettingStarted],
    recommendedExampleIds: [EXAMPLE_IDS.queryLookahead, EXAMPLE_IDS.generatedQuery],
    recommendedRecipeIds: [RECIPE_IDS.queryLookaheadShape, RECIPE_IDS.generatedFiltersOrderPagination],
    stability: 'stable',
    confidence: 'high',
  },
  {
    id: 'playground-runtime-differs-from-upstream-guidance',
    title: 'Playground Runtime Differs From Upstream Guidance',
    summary: 'A website demo behavior does not fully match the upstream docs or source-backed expectations.',
    description: 'The current playground is an adapted showcase runtime, so upstream docs and canonical knowledge should win whenever the website demo and source-backed guidance do not perfectly align.',
    topics: ['troubleshooting', 'playground', 'parity', 'mcp'],
    sourcePath: 'content/graphql-gene/docs/mcp-server-setup.md',
    symptoms: [
      'The playground demonstrates the feature, but the implementation details differ from upstream docs.',
      'The team is unsure whether to trust the website demo or the source-backed documentation.',
    ],
    stages: ['runtime', 'query'],
    scenarios: ['model-to-schema', 'query-lookahead', 'polymorphic-blocks', 'directive-middleware'],
    likelyCauses: [
      'The current website runtime is an adapted demo engine rather than the upstream product runtime.',
      'Demo ergonomics were prioritized over strict source parity in the website execution layer.',
    ],
    recommendedChecks: [
      'Prefer the upstream-aligned docs and canonical knowledge entries when they conflict with the playground.',
      'Treat the playground as a capability showcase rather than the primary truth source.',
      'Use MCP resources and canonical docs to confirm product behavior before coding against the demo.',
    ],
    recommendedDocIds: [DOC_IDS.mcpServerSetup, DOC_IDS.gettingStarted],
    recommendedExampleIds: [EXAMPLE_IDS.modelToSchema, EXAMPLE_IDS.queryLookahead, EXAMPLE_IDS.polymorphicBlocks, EXAMPLE_IDS.directiveMiddleware],
    recommendedRecipeIds: [RECIPE_IDS.sequelizeBootstrap, RECIPE_IDS.queryLookaheadShape, RECIPE_IDS.directiveMiddlewareAuth, RECIPE_IDS.polymorphicContentBlocks],
    stability: 'stable',
    confidence: 'high',
  },
]

export function getSiteCuratedExampleKnowledge() {
  return siteCuratedExampleKnowledge.map(entry => ({ ...entry }))
}

export function getSitePluginKnowledge() {
  return sitePluginKnowledge.map(entry => ({ ...entry }))
}

export function getSiteRecipeKnowledge() {
  return siteRecipeKnowledge.map(entry => ({ ...entry }))
}

export function getSiteTroubleshootingKnowledge() {
  return siteTroubleshootingKnowledge.map(entry => ({ ...entry }))
}
